# Generated by Django 5.2.13 on 2026-04-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_first_name_and_more'),
        ('courses', '0002_alter_topic_course_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='allowed_depts',
            field=models.ManyToManyField(blank=True, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='allowed_levels',
            field=models.ManyToManyField(blank=True, to='accounts.level'),
        ),
    ]
